apiVersion: v1
kind: Service
metadata:
  name: nginx-external-dns
  labels: 
    app: nginx-external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.tech-talk-ntt.com
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx-external-dns

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-external-dns
spec:
  template:
    metadata:
      labels:
        app: nginx-external-dns
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http